In [2]:
import pandas as pd
import openpyxl

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
df = pd.read_excel("../input_files/excel_file.xlsx")

In [5]:
df

,Brand,Sector,Silhouette,Category,Sub-Category,Season,Seasonless - Style Number,Image,Designated Supplier (External),Seasonless -,Is Seasonless,VSD Style#,Seasonless - Generic Article,Seasonless - SAP Description,Seasonless - Generic Article Description,Carry Over,Seasonless - Style Name,Seasonless - Status,Seasonless - Innovation Product,Seasonless - Innovation Protected,Product Sources,Unnamed: 21,Seasonless - Solids / Prints Care Codes,Seasonless - All Graphic / Foil Prints Care Codes,Seasonless - Diamante Care Codes,Seasonless - Wash Care Codes,Seasonless - Additional Packaging Requirements,Seasonless - Silhouette Code,Seasonless - Inseam Measurements,Seasonless - Care Label Text,Seasonless - Main Label Text,Seasonless - Care Label Exceptions,Seasonless - Product Content Summary,Seasonless - CSG Notes,Size Range,Sizes,MAT Assortment Status (Product),MAT Adoption Status (Product),MAT Assortment Sizing (Product),Data Sheets,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Modified,Modified By,IT Internal
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Product Source,Supplier Regional Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sizing Method,Sizes,Base Composition,Modified,Modified By,Created,Created By,NaT,NaN,NaN
1,PINK,Intimates,BOYSHORT,Panties,NaN,Holiday 2026,10240242.0,NaN,MAS,10240242 PINK INTIMATES CODE BOYSHORT SP24,0.0,416213.0,11245830.0,PINK INTMTS CODE BOY,PINK INTMTS CODE BOY,1.0,PINK INTIMATES CODE BOYSHORT,Candidate,0.0,0.0,10240242 - MAS,NaN,MWW001,MWC003,HWC004,NaN,NaN,Shortie,Solids/Prints: MWW001; All Graphics/Foil Print...,"Solids / Prints Care Codes - MWW001, All Graph...",",Shortie",NaN,Panties & Swim Bottoms - (XXS - XXL) & O/S** (...,Panties & Swim Bottoms - (XXS - XXL) & O/S****...,Alpha,XXS-XXL,Active,Adopted,"XS, S, M, L, XL, XXL, XXS",NaN,NaN,NaN,2025-12-02 20:16:00,Melissa Fernandez,2025-12-02 20:16:00,Melissa Fernandez,2026-04-30 16:26:00,Sajani De Silva,1.753853e+09

In [6]:
pd.reset_option("display.max_columns")

In [11]:
df = df[['Seasonless - Silhouette Code', 'Seasonless - Product Content Summary']]
df = df.dropna()
df

,Seasonless - Silhouette Code,Seasonless - Product Content Summary
1,Shortie,Panties & Swim Bottoms - (XXS - XXL) & O/S** (...

In [8]:
df.columns

Index(['Brand', 'Sector', 'Silhouette', 'Category', 'Sub-Category', 'Season',
       'Seasonless - Style Number', 'Image', 'Designated Supplier (External)',
       'Seasonless -', 'Is Seasonless', 'VSD Style#',
       'Seasonless - Generic Article', 'Seasonless - SAP Description',
       'Seasonless - Generic Article Description', 'Carry Over',
       'Seasonless - Style Name', 'Seasonless - Status',
       'Seasonless - Innovation Product', 'Seasonless - Innovation Protected',
       'Product Sources', 'Unnamed: 21',
       'Seasonless - Solids / Prints Care Codes',
       'Seasonless - All Graphic / Foil Prints Care Codes',
       'Seasonless - Diamante Care Codes', 'Seasonless - Wash Care Codes',
       'Seasonless - Additional Packaging Requirements',
       'Seasonless - Silhouette Code', 'Seasonless - Inseam Measurements',
       'Seasonless - Care Label Text', 'Seasonless - Main Label Text',
       'Seasonless - Care Label Exceptions',
       'Seasonless - Product Content Summary', 'Seasonless - CSG Notes',
       'Size Range', 'Sizes', 'MAT Assortment Status (Product)',
       'MAT Adoption Status (Product)', 'MAT Assortment Sizing (Product)',
       'Data Sheets', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Modified', 'Modified By',
       'IT Internal'],
      dtype='str')